import { ProductoHarryPotter } from './types';
export const questions = [
  {
    question: 'What quality do you value more in a friend?',
    options: {
      Gryffindor: 'Bravery',
      Hufflepuff: 'Loyalty',
      Ravenclaw: 'Wisdom',
      Slytherin: 'Ambition',
    },
  },
  {
    question: 'What would you do if you saw someone breaking the rules?',
    options: {
      Gryffindor: 'Confront them directly',
      Hufflepuff: 'Try to reason with them',
      Ravenclaw: 'Report them to the authorities',
      Slytherin: 'Look for ways to take advantage of the situation',
    },
  },
  {
    question: 'What subject would be your favorite in Hogwarts?',
    options: {
      Gryffindor: 'Defense Against the Dark Arts',
      Hufflepuff: 'Magical Creatures',
      Ravenclaw: 'Arithmancy',
      Slytherin: 'Potions',
    },
  },
  {
    question: 'What is your greatest goal in life?',
    options: {
      Gryffindor: 'Doing what is right and protecting others',
      Hufflepuff: 'Being part of a strong community',
      Ravenclaw: 'Discovering and learning new things',
      Slytherin: 'Achieving success and power',
    },
  },
  {
    question: 'What magical creature fascinates you most?',
    options: {
      Gryffindor: 'Hippogriff',
      Hufflepuff: 'Niffler',
      Ravenclaw: 'Phoenix',
      Slytherin: 'Basilisk',
    },
  },
];

export const productosHarryPotter: ProductoHarryPotter[] = [
  {
    id: 1,
    nombre: 'Personalized Magic Wand',
    descripcion:
      'Personalized magic wand inspired by characters and spells from Harry Potter.',
    precio: 19990,
    categoria: 'Accesorios',
    stock: 50,
    imagen: '/img/product/p1.jpg',
    peso: '0.2kg',
    dimensiones: '35cm x 2cm',
    envio: 'International shipping available',
  },
  {
    id: 2,
    nombre: 'Gryffindor Scarf',
    descripcion: 'Wool scarf with Gryffindor house colors.',
    precio: 14990,
    categoria: 'Ropa',
    stock: 30,
    imagen: '/img/product/p2.webp',
    peso: '0.3kg',
    dimensiones: '180cm x 25cm',
    envio: 'Shipping within the country only',
  },
  {
    id: 3,
    nombre: "Hermione's Time-Turner Necklace",
    descripcion:
      'Time-turner necklace similar to the one used by Hermione in the series.',
    precio: 12990,
    categoria: 'Accesorios',
    stock: 20,
    imagen: '/img/product/14.webp',
    peso: '0.05kg',
    dimensiones: '5cm x 5cm',
    envio: 'International shipping available',
  },
  {
    id: 4,
    nombre: "Marauder's Map",
    descripcion: "Interactive print of the Marauder's Map.",
    precio: 17990,
    categoria: 'Decoración',
    stock: 15,
    imagen: '/img/product/p4.webp',
    peso: '0.15kg',
    dimensiones: '60cm x 40cm',
    envio: 'International shipping available',
  },
  {
    id: 5,
    nombre: "Bertie Bott's Every Flavor Beans",
    descripcion:
      'Candy box with random flavors inspired by the magical world of Harry Potter.',
    precio: 6990,
    categoria: 'Dulces',
    stock: 100,
    imagen: '/img/product/p5.jpeg',
    peso: '0.1kg',
    dimensiones: '10cm x 5cm x 5cm',
    envio: 'Shipping within the country only',
  },
  {
    id: 6,
    nombre: 'Harry Potter Mug',
    descripcion:
      'Mug with a color-changing design that shows images from the Harry Potter world when you add hot liquid.',
    precio: 9990,
    categoria: 'Hogar',
    stock: 40,
    imagen: '/img/product/p6-1.jpg',
    peso: '0.35kg',
    dimensiones: '12cm x 8cm',
    envio: 'International shipping available',
  },
  {
    id: 7,
    nombre: "Tom Riddle's Diary",
    descripcion:
      'Diary with a design inspired by the one used by Tom Riddle in the series.',
    precio: 15990,
    categoria: 'Papelería',
    stock: 25,
    imagen: '/img/product/p7.jpg',
    peso: '0.4kg',
    dimensiones: '20cm x 15cm',
    envio: 'International shipping available',
  },
  {
    id: 8,
    nombre: 'LEGO Harry Potter - Great Hall',
    descripcion:
      'LEGO set of the Great Hall of Hogwarts, including character minifigures.',
    precio: 59990,
    categoria: 'Juguetes',
    stock: 10,
    imagen: '/img/product/p8.jpg',
    peso: '1.2kg',
    dimensiones: '40cm x 30cm x 10cm',
    envio: 'International shipping available',
  },
  {
    id: 9,
    nombre: 'Hogwarts Crest Pillow',
    descripcion:
      'Decorative pillow with the Hogwarts crest, perfect for your bed or sofa.',
    precio: 11990,
    categoria: 'Decoración',
    stock: 35,
    imagen: '/img/product/p12.avif',
    peso: '0.5kg',
    dimensiones: '40cm x 40cm',
    envio: 'Shipping within the country only',
  },
  {
    id: 10,
    nombre: 'Dark Mark Hoodie',
    descripcion: 'Black hoodie with the Dark Mark design.',
    precio: 24990,
    categoria: 'Ropa',
    stock: 20,
    imagen: '/img/product/p13.webp',
    peso: '0.6kg',
    dimensiones: 'Tallas S, M, L, XL',
    envio: 'International shipping available',
  },
];
