import './styles/globals.css';
import { Footer } from './components/footer';
import { Navbar } from './components/navbar';

export const metadata = {
  title: 'Harry Potter Page',
  description: 'Generated by Next.js',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="min-h-screen flex flex-col justify-between overflow-x-hidden bg-stars">
        <Navbar />
        <main className="flex-grow max-w-full overflow-hidden mx-auto">
          {children}
        </main>
        <Footer />
      </body>
    </html>
  );
}
