import './styles/globals.css';

export const metadata = {
  title: 'Harry Potter Page',
  description: 'Generated by Next.js',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" href="/img/logo.png" />
      </head>
      <body className="min-h-screen flex flex-col justify-between overflow-x-hidden bg-stars">
        <main className="flex-grow max-w-full overflow-hidden mx-auto">
          {children}
        </main>
      </body>
    </html>
  );
}
